### ISSUE TITLE
menu crash

### ISSUE THREAD

**Issue by kmmndr** [DizzyThermal/Auto-Away#1]
Hi,

Very nice idea for the project !
But Auto-Away v1.2.1 always crash when entering any of the two menus.
Any idea how to solve this issue ?

**Comment by DizzyThermal** [comment]
Hey Thomas!

Thanks for try Auto-Away, I'm sorry you're having issues with it :(

When you get a Force Close, have you been sending the report?  It makes it
a bit easier on my end if I can read the Trace of where it crashed and
why.. If you know how to generate a _logcat_ this is even better!  If you
have _adb_ installed on your computer and have Android Debugging Enabled on
your device you can open a command prompt and type:

_adb logcat -v long > Auto-Away.txt_
*
*
Open Auto-Away and make it crash, then go back to the Command Prompt and
hit: _CTRL-C.._
*
*
Then send the Auto-Away.txt log..  I will look into it though and let you
know what I find!  Thanks Thomas!

-Stephen

On Fri, Apr 19, 2013 at 2:46 AM, Thomas Kienlen notifications@github.comwrote:

> Hi,
> 
> Very nice idea for the project !
> But Auto-Away v1.2.1 always crash when entering any of the two menus.
> Any idea how to solve this issue ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DizzyThermal/Auto-Away/issues/1
> .

## 

Stephen Diniz https://plus.google.com/109941711245243963357/
DizzyThermal@gmail.com

**Comment by kmmndr** [comment]
Here you are :-)

```
I/ActivityManager(  176): Starting: Intent { cmp=com.teamdc.stephendiniz.autoaway/.Activity_Messages } from pid 4477
I/dalvikvm( 4477): Could not find method com.teamdc.stephendiniz.autoaway.Activity_Messages.getActionBar, referenced from method com.teamdc.stephendiniz.autoaway.Activity_Messages.onCreate
W/dalvikvm( 4477): VFY: unable to resolve virtual method 308: Lcom/teamdc/stephendiniz/autoaway/Activity_Messages;.getActionBar ()Landroid/app/ActionBar;
D/dalvikvm( 4477): VFY: replacing opcode 0x6e at 0x0003
D/dalvikvm( 4477): VFY: dead code 0x0006-0023 in Lcom/teamdc/stephendiniz/autoaway/Activity_Messages;.onCreate (Landroid/os/Bundle;)V
D/AndroidRuntime( 4477): Shutting down VM
W/dalvikvm( 4477): threadid=1: thread exiting with uncaught exception (group=0x40018560)
E/AndroidRuntime( 4477): FATAL EXCEPTION: main
E/AndroidRuntime( 4477): java.lang.NoSuchMethodError: com.teamdc.stephendiniz.autoaway.Activity_Messages.getActionBar
E/AndroidRuntime( 4477):    at com.teamdc.stephendiniz.autoaway.Activity_Messages.onCreate(Activity_Messages.java:59)
E/AndroidRuntime( 4477):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
E/AndroidRuntime( 4477):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1722)
E/AndroidRuntime( 4477):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)
E/AndroidRuntime( 4477):    at android.app.ActivityThread.access$1500(ActivityThread.java:123)
E/AndroidRuntime( 4477):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
E/AndroidRuntime( 4477):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4477):    at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime( 4477):    at android.app.ActivityThread.main(ActivityThread.java:3835)
E/AndroidRuntime( 4477):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4477):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 4477):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
E/AndroidRuntime( 4477):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
E/AndroidRuntime( 4477):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  176):   Force finishing activity com.teamdc.stephendiniz.autoaway/.Activity_Messages
W/ActivityManager(  176):   Force finishing activity com.teamdc.stephendiniz.autoaway/.Activity_Main
D/dalvikvm(  358): GC_CONCURRENT freed 437K, 52% free 2795K/5767K, external 311K/823K, paused 6ms+11ms
W/ActivityManager(  176): Activity pause timeout for HistoryRecord{40ab8f88 com.teamdc.stephendiniz.autoaway/.Activity_Messages}
I/Process ( 4477): Sending signal. PID: 4477 SIG: 9
I/WindowManager(  176): WIN DEATH: Window{40aa3d70 com.teamdc.stephendiniz.autoaway/com.teamdc.stephendiniz.autoaway.Activity_Main paused=true}
I/ActivityManager(  176): Process com.teamdc.stephendiniz.autoaway (pid 4477) has died.
```

**Comment by DizzyThermal** [comment]
What version of Android are you running?

**Comment by DizzyThermal** [comment]
Hey Thomas, let me know how the new update works!  Hopefully I squashed
that bug!

On Fri, Apr 19, 2013 at 1:43 PM, Stephen Diniz dizzythermal@gmail.comwrote:

> What version of Android are you running?
> On Apr 19, 2013 1:42 PM, "Thomas Kienlen" notifications@github.com
> wrote:
> 
> > Here you are :-)
> > 
> > I/ActivityManager(  176): Starting: Intent { cmp=com.teamdc.stephendiniz.autoaway/.Activity_Messages } from pid 4477
> > I/dalvikvm( 4477): Could not find method com.teamdc.stephendiniz.autoaway.Activity_Messages.getActionBar, referenced from method com.teamdc.stephendiniz.autoaway.Activity_Messages.onCreate
> > W/dalvikvm( 4477): VFY: unable to resolve virtual method 308: Lcom/teamdc/stephendiniz/autoaway/Activity_Messages;.getActionBar ()Landroid/app/ActionBar;
> > D/dalvikvm( 4477): VFY: replacing opcode 0x6e at 0x0003
> > D/dalvikvm( 4477): VFY: dead code 0x0006-0023 in Lcom/teamdc/stephendiniz/autoaway/Activity_Messages;.onCreate (Landroid/os/Bundle;)V
> > D/AndroidRuntime( 4477): Shutting down VM
> > W/dalvikvm( 4477): threadid=1: thread exiting with uncaught exception (group=0x40018560)
> > E/AndroidRuntime( 4477): FATAL EXCEPTION: main
> > E/AndroidRuntime( 4477): java.lang.NoSuchMethodError: com.teamdc.stephendiniz.autoaway.Activity_Messages.getActionBar
> > E/AndroidRuntime( 4477):    at com.teamdc.stephendiniz.autoaway.Activity_Messages.onCreate(Activity_Messages.java:59)
> > E/AndroidRuntime( 4477):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
> > E/AndroidRuntime( 4477):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1722)
> > E/AndroidRuntime( 4477):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)
> > E/AndroidRuntime( 4477):    at android.app.ActivityThread.access$1500(ActivityThread.java:123)
> > E/AndroidRuntime( 4477):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
> > E/AndroidRuntime( 4477):    at android.os.Handler.dispatchMessage(Handler.java:99)
> > E/AndroidRuntime( 4477):    at android.os.Looper.loop(Looper.java:130)
> > E/AndroidRuntime( 4477):    at android.app.ActivityThread.main(ActivityThread.java:3835)
> > E/AndroidRuntime( 4477):    at java.lang.reflect.Method.invokeNative(Native Method)
> > E/AndroidRuntime( 4477):    at java.lang.reflect.Method.invoke(Method.java:507)
> > E/AndroidRuntime( 4477):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
> > E/AndroidRuntime( 4477):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
> > E/AndroidRuntime( 4477):    at dalvik.system.NativeStart.main(Native Method)
> > W/ActivityManager(  176):   Force finishing activity com.teamdc.stephendiniz.autoaway/.Activity_Messages
> > W/ActivityManager(  176):   Force finishing activity com.teamdc.stephendiniz.autoaway/.Activity_Main
> > D/dalvikvm(  358): GC_CONCURRENT freed 437K, 52% free 2795K/5767K, external 311K/823K, paused 6ms+11ms
> > W/ActivityManager(  176): Activity pause timeout for HistoryRecord{40ab8f88 com.teamdc.stephendiniz.autoaway/.Activity_Messages}
> > I/Process ( 4477): Sending signal. PID: 4477 SIG: 9
> > I/WindowManager(  176): WIN DEATH: Window{40aa3d70 com.teamdc.stephendiniz.autoaway/com.teamdc.stephendiniz.autoaway.Activity_Main paused=true}
> > I/ActivityManager(  176): Process com.teamdc.stephendiniz.autoaway (pid 4477) has died.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/DizzyThermal/Auto-Away/issues/1#issuecomment-16668440
> > .

## 

Stephen Diniz https://plus.google.com/109941711245243963357/
DizzyThermal@gmail.com

**Comment by kmmndr** [comment]
Thank you very much for this patch !! :-)
